//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS_AUTHORS
    {
        public int BA_BK { get; set; }
        public int BA_AU { get; set; }
        public int BA_ID { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        public virtual BOOKS BOOKS { get; set; }
    }
}
