//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS_SOURCES
    {
        public int BS_ID { get; set; }
        public int BS_BK { get; set; }
        public string BS_S { get; set; }
        public string BS_INFO { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
    }
}
