//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS()
        {
            this.BOOKS_REVIEWS = new HashSet<BOOKS_REVIEWS>();
            this.BOOKS_SOURCES = new HashSet<BOOKS_SOURCES>();
            this.BOOKS_AUTHORS = new HashSet<BOOKS_AUTHORS>();
            this.BOOKS_GENRES = new HashSet<BOOKS_GENRES>();
        }
    
        public int BK_ID { get; set; }
        public string BK_NAME { get; set; }
        public string BK_INFO { get; set; }
        public Nullable<int> BK_RATING { get; set; }
        public int BK_DAC { get; set; }
    
        public virtual DICTIONARY_AGE_CATEGORIES DICTIONARY_AGE_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKS_REVIEWS> BOOKS_REVIEWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKS_SOURCES> BOOKS_SOURCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKS_AUTHORS> BOOKS_AUTHORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKS_GENRES> BOOKS_GENRES { get; set; }
    }
}
