//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICTIONARY_AGE_CATEGORIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICTIONARY_AGE_CATEGORIES()
        {
            this.BOOKS = new HashSet<BOOKS>();
        }
    
        public int DAC_ID { get; set; }
        public string DAC_NAME { get; set; }
        public Nullable<int> DAC_FROM { get; set; }
        public Nullable<int> DAC_TO { get; set; }
        public string DAC_INFO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKS> BOOKS { get; set; }
    }
}
