//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORS_REVIEWS
    {
        public int AR_ID { get; set; }
        public int AR_AU { get; set; }
        public string AR_R { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
    }
}
