//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS_AUTHORS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS_AUTHORS()
        {
            this.AWARDS = new HashSet<AWARDS>();
        }
    
        public int BA_ID { get; set; }
        public int BA_BK { get; set; }
        public int BA_AU { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AWARDS> AWARDS { get; set; }
        public virtual BOOKS BOOKS { get; set; }
    }
}
